name: universal_internet_checker
description: Listenable internet check for Flutter Web and Mobile
version: 0.1.0
homepage: https://github.com/iwalpola/universal_internet_checker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  doh_client:
    path: '../doh_client'
  flutter:
    sdk: flutter
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

publish_to: none